// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Milekic.YoLo")>]
[<assembly: AssemblyProductAttribute("Milekic.YoLo")>]
[<assembly: AssemblyVersionAttribute("2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Milekic.YoLo"
    let [<Literal>] AssemblyProduct = "Milekic.YoLo"
    let [<Literal>] AssemblyVersion = "2.0"
    let [<Literal>] AssemblyFileVersion = "2.0"
