// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Milekic.YoLo")>]
[<assembly: AssemblyProductAttribute("Milekic.YoLo")>]
[<assembly: AssemblyVersionAttribute("0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Milekic.YoLo"
    let [<Literal>] AssemblyProduct = "Milekic.YoLo"
    let [<Literal>] AssemblyVersion = "0.2"
    let [<Literal>] AssemblyFileVersion = "0.2"
