// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Milekic.YoLo")>]
[<assembly: AssemblyProductAttribute("Milekic.YoLo")>]
[<assembly: AssemblyVersionAttribute("1.1")>]
[<assembly: AssemblyFileVersionAttribute("1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Milekic.YoLo"
    let [<Literal>] AssemblyProduct = "Milekic.YoLo"
    let [<Literal>] AssemblyVersion = "1.1"
    let [<Literal>] AssemblyFileVersion = "1.1"
